# Remove this file after year 2020

- id: prettier
  name: prettier
  entry: echo prettier support for pre-commit have been moved to https://github.com/prettier/pre-commit, please checkout the new repository. && exit 1
  language: system
